BbcTestList = [
["http://www.bbc.co.uk/iplayer/episode/p03rkqcv/shakespeare-lives-the-works" ] ,
["http://www.bbc.co.uk/iplayer/episode/b05s86by/the-disappearance-episode-3" ] ,
["http://www.bbc.co.uk/iplayer/episode/p03qq41l/shakespeare-lives-ballet-opera-and-the-bard" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07j554j/holby-city-series-18-38-another-day-in-paradise-part-one" ] ,
["http://www.bbc.co.uk/iplayer/episode/b01n8hl9/" ] ,
["http://www.bbc.co.uk/iplayer/episode/p03ymv61/the-insider-1-reggie-yates-in-a-texan-jail" ] ,
["http://www.bbc.co.uk/iplayer/episode/p043lxs0/making-a-slave-1-trapped" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07nwvg1/eastenders-08082016" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07nxr6l/an-hour-to-save-your-life-series-3-episode-1" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07p0q0g/red-rock-episode-23" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07nswft/the-mystery-of-van-goghs-ear" ] ,
["http://www.bbc.co.uk/iplayer/episode/p0429dh0/olympic-diving-final-mens-synchronised-3m-springboard-wednesday" ] ,
["http://www.bbc.co.uk/iplayer/episode/b07nsxkk/horizon-20152016-13-inside-cern"],
]