def createSoupObject(url,fileName):
	
	requestObject = requests.get(url)

	# fileHandler = open("requests.txt", "w")
	# fileHandler.write(requestObject.text)
	# fileHandler.close() 
	
	soupObject = BeautifulSoup(requestObject.text,from_encoding="utf8")
	#soupObject1 = BeautifulSoup(requestObject.text,"lxml")
	#print(self.soupObject.original_encoding)

	fh = open(fileName, "w")
	fh.write(str(soupObject))
	fh.close()		

	pass

def deleteUnnecessaryfiles(debug,fileName,title,extension):

	if not debug:
		try:
			os.remove(self.fileName)
			os.remove(self.title+".vtt")
		except:
			pass

def downloadXMLTranscript(encoding, FinalUrl):

    """
    This function fetches the captions and writes them into a file in XML
    """

    try:
        self.requestObjectv = requests.get(self.SubtitleUrl)
        self.requestObjectv.encoding = encoding
        print("Creating ~  '%s.xml' ..."%(self.title))
        subsFileHandler = open(self.title + ".xml","w")
        

        if not self.requestObjectv.text:
            if FinalUrl:
                FinalUrl += autoGeneratedUrl
                self.requestObjectv = requests.get(FinalUrl)
            else:
                return 0
        self.requestObjectv = BeautifulSoup(self.requestObjectv.text)
        subsFileHandler.write(str(self.requestObjectv))
        subsFileHandler.close()

        return 1

    except:
        return 0
    pass
    
def downloadDfxpTranscript(SubsLink):

		"""
		This function fetches the captions and writes them into a file in VTT format
		"""
		try:
			subRequestObject = requests.get(SubsLink)
			#print(subRequestObject.text)
			subRequestObject.encoding = 'utf-8'
			
			subsFileHandler = open(self.title + ".dfxp","w")
			print("Creating ~  '%s.dfxp' ..."%(self.title))			
			subsFileHandler.write(subRequestObject.text)
			subsFileHandler.close()
			return 1
		
		except:
			return 0
		
		pass
	

def getTitleHTMLTags():

    """
    This function returns the title of the video. This is also used for naming the file.

    <title>Crunchyroll - Watch Naruto Shippuden: Season 17 Episode 464 - Ninshu: The Ninja Creed</title>
    
    """
    
    try:
        self.title = self.soupObject.title.string.strip()

    except:
        self.title = "Subtitles"

    pass